### ISSUE TITLE
Lcobucci\JWT 4 upgrade issues

### ISSUE THREAD

**Issue by victornieto** [okta/okta-sdk-php#122]
Seems ```"lcobucci/jwt": "^4.0@alpha"``` library has some breaking changes  as explained in this post -> https://lcobucci-jwt.readthedocs.io/en/latest/upgrading/
Those changes are not implemented in class Okta\Utilities\PrivateKeyAuthentication which is trying to instantiate the Key interface ```$this->privateKey = new Key($privateKey);``` causing errors when the client is using PRIVATE_KEY authorization mode.

**Comment by bretterer** [comment]
@victornieto this is a known issue and we have it in our list to take a look at. 

internal ref: OKTA-389602

**Comment by bretterer** [comment]
This has been updated in the branch `update_deps` and will be released soon
