### ISSUE TITLE
Compatibility with laravel/framework 8.0

### ISSUE THREAD

**Issue by victornieto** [okta/okta-sdk-php#123]
We need the okta sdk integrated in a laravel 8 project. 
These libraries below are causing conflicts:

```
"symfony/yaml": "^3.2|^4.3",
"illuminate/collections": "8.29.0",
"guzzlehttp/psr7": "1.7.0",
"vlucas/phpdotenv": "^3.3|^4.1",
```

Updating those to these versions spec is solving the issue on our side
```
"symfony/yaml": "^3.2|^4.3|^5.0",
"illuminate/collections": "^8.29.0",
"guzzlehttp/psr7": "^1.7.0",
"vlucas/phpdotenv": "^3.3|^4.1|^5.3",
```

Not sure if this configuration is breaking something internally though.

**Comment by bretterer** [comment]
@victornieto, Thank you for reporting this. We will add this to our tasks to take a look at.

Internal Ref: OKTA-389602

**Comment by bretterer** [comment]
The branch `update_deps` will resolve this.  I have tested basic functionality with PHP 8.0.2 and Laravel 8.40.0

**Comment by victornieto** [comment]
Excellent. We'll give it a try

**Comment by bretterer** [comment]
@victornieto please let me know if that works for you
