### ISSUE TITLE
Call to undefined function Okta\posix_getpwuid()

### ISSUE THREAD

**Issue by deepakkakran** [okta/okta-sdk-php#42]
While initializing the Okta Client, it is giving an error

```
Type: Error
Message: Call to undefined function Okta\posix_getpwuid()
Filename: C:\Bitnami\wampstack-5.6.28-1\apache2\htdocs\project\website\vendor\okta\sdk\src\ClientBuilder.php
Line Number: 61
```

**Comment by bretterer** [comment]
Thanks for reporting this.  I will take a look at this, but at first glance, it seems that `posix_getpwuid` is not available on windows based machines.

**Comment by c3c** [comment]
When deploying to Azure, I get the same error.

**Comment by bretterer** [comment]
Good to know.  thank you @c3c ... I am guessing it is the same issue since i believe Azure uses windows based machines. (not sure on that though, have not looked into it on the Azure side)

**Comment by c3c** [comment]
Yes, the app I'm running is on a Windows OS. As a quick workaround I added the following:

`function posix_getpwuid($id) {}`
`function posix_getuid() {}`

**Comment by bretterer** [comment]
If you want to make a PR against develop, I am happy to take a look and get it merged in today if all looks good.  @c3c

**Comment by bretterer** [comment]
@c3c and @deepakkakran 
I am still working on this, but I may have a fix in place and would love some input form you in your system.  I am just checking to see if the function exists before using it.  This is only for auto-discovery of the okta.yaml file.  On windows, you will just have to manually define it using the Client Builders method `setConfigFileLocation`
