### ISSUE TITLE
Support for symfony 4.2

### ISSUE THREAD

**Issue by kezek** [okta/okta-sdk-php#62]
1. Tests pass with symfony/yaml 3.4.* and tightenco/collect 5.6.* and they don't have any dependency conflicts with symfony 4.2.*

2. tightenco/collect 5.5.33 can't work with symfony 4.2.* due to locked dependecy symfony/var-dumper: ~3.3

3. But tightenco/collect 5.6.* only supports php 7.1.3+ (as well as symfony 4.2)

4. Symfony 4.2 also requires the symfony/yaml to be at 'self' version (as in 4.2). When upgrading symfony/yaml to 4.2 I noticed some unit tests failing (related to space after comma , not sure if a big deal or not)

_Originally posted by @kezek in https://github.com/okta/okta-sdk-php/pull/61#issuecomment-451420674_

**Comment by hackzilla** [comment]
Some documentation on how to use this library with Symfony Guard would also be helpful.
Also Symfony 5.0 will be released in November 2019

**Comment by bretterer** [comment]
@hezek, I have an update ready to go out with a bunch of dependency updates.  It will be out shortly
