### ISSUE TITLE
tightenco/collect namespace conflicts.

### ISSUE THREAD

**Issue by curricula** [okta/okta-sdk-php#63]
Im unable to install this package through composer due to namespace conflicts with your "tightenco/collect": "5.5.33" package and Laravel >= 5.6.*.

I believe newer versions of Collect have corrected this issue though.

**Comment by curricula** [comment]
An update... Running composer require okta/sdk with Laravel 5.6.* returns.

`- Installation request for symfony/http-kernel (locked at v4.2.4) -> satisfiable by symfony/http-kernel[v4.2.4].
    - Installation request for okta/sdk ^1.1 -> satisfiable by okta/sdk[1.1.0].
    - don't install laravel/framework v5.6.39|don't install illuminate/support v5.5.33
    - don't install illuminate/support v5.5.33|remove laravel/framework v5.6.39
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.6.39
    - okta/sdk 1.1.0 requires tightenco/collect 5.5.33 -> satisfiable by illuminate/support[v5.5.33], tightenco/collect[v5.5.33].
    - Conclusion: don't install tightenco/collect v5.5.33
    - Installation request for laravel/framework (locked at v5.6.39, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.39].`

**Comment by LarBearrr** [comment]
I'm having similar issues. I'm trying to use Laravel 5.5. I got past the composer problems by downgrading to 5.5.33. However, now I have issues when trying to get a users groups:

```
$client = (new \Okta\ClientBuilder())
            ->setConfigFileLocation(base_path('okta.yaml'))
            ->build();

        debug($client);

        $user = new \Okta\Users\User();
        $foundUser = $user->get('USER_ID');
        dump($foundUser->getGroups());
```

which throws:
`Class 'Tightenco\Collect\Support\Collection' not found`

**Comment by bretterer** [comment]
I have upgraded tightenco/collect to 5.8.31.  We chose to go with this package because it only contains the collection object that laravel has.  Since laravel does not provide the collect package outside of all the others it would install, we decided to only include this port.

**Comment by LarBearrr** [comment]
@bretterer Thanks for the update. Will this solve the issue with using this package in Laravel apps?

**Comment by bretterer** [comment]
@LarBearrr it should, but when it gets into the develop branch, please let me know if it doesn't

**Comment by LarBearrr** [comment]
@bretterer Unfortunately I'm still having issues:
```
$ composer require okta/sdk
Using version ^1.1 for okta/sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for okta/sdk ^1.1 -> satisfiable by okta/sdk[1.1.0].
    - Conclusion: remove laravel/framework v5.5.46
    - Conclusion: don't install laravel/framework v5.5.46
    - okta/sdk 1.1.0 requires tightenco/collect 5.5.33 -> satisfiable by laravel/framework[v5.5.33], illuminate/support[v5.5.33], tightenco/collect[v5.5.33].
    - Can only install one of: laravel/framework[v5.5.33, v5.5.46].
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.5.46
    - don't install tightenco/collect v5.5.33|don't install laravel/framework v5.5.46
    - Installation request for laravel/framework (locked at v5.5.46, required as 5.5.*@dev) -> satisfiable by laravel/framework[v5.5.46].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by bretterer** [comment]
You were still using release 1.1.0

There is now a release for 1.2.0 which includes the updates.

**Comment by LarBearrr** [comment]
How do I get that release?  `composer require okta/sdk:'1.2.0'` is failing: `Could not find package okta/sdk in a version matching 1.2.0`
