### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by GinoPane** [okta/okta-sdk-php#71]
Hi!

Are there maybe any existing ports of this library to PHP 5.6?
We need to integrate this library with a legacy system.

**Comment by bretterer** [comment]
Hi @GinoPane, There are no officially supported ports of this sdk to work with 5.6   

We require modern, up-to-date versions of PHP for our library for some of the features we are using.

**Comment by GinoPane** [comment]
Yeah, I see. It is fine of course for the library, but sad for legacy projects 😄
