### ISSUE TITLE
Unable to activate a deactivated user

### ISSUE THREAD

**Issue by LarBearrr** [okta/okta-sdk-php#73]
I am trying to manage users by deactivating their Okta account from my custom web app. I can make the call using the SDK to deactivate the user; however, when I try to reactivate them, I am getting errors that the resource does not exist.

The code below works to deactivate the user:
```
try {
            $user = new \Okta\Users\User();
            $foundUser = $user->get($model->okta_id);
            $foundUser->endAllSessions(true);
            $foundUser->deactivate();
        } catch (Exception $e) {
            $this->handleError($e);
        }
```

This code below to activate the user is failing:
```
try {
            $userToRestore = User::withTrashed()->find($recordId);
            $user = new \Okta\Users\User();
            $foundUser = $user->get(/*OKTA_ID*/);
            $foundUser->activate();
        } catch (Exception $e) {
            $this->handleError($e);
        }
```
which produces the following error:
![image](https://user-images.githubusercontent.com/28734844/64783817-52732300-d52e-11e9-8107-42d23ce21a12.png)

I have been able to use the `suspend()` method on the `Okta\Users\User` class, although I would prefer to deactivate the account so I can send an activation email when the user is re-activated.

@bretterer Do you have any thoughts?

Thanks!

**Comment by LarBearrr** [comment]
@bretterer I'm certain the user exists in the organization. The only request I am making is to deactivate the user, as described in my code sample above.

I have a similar issue regarding creating new users from our custom web app. Is it possible to "create" the user in our organization without sending the activation email? We want to "stage" users in the organization and use a queue worker to fire off the activation emails.

**Comment by bretterer** [comment]
The User object's create method allows for you to pass query params into it

https://github.com/okta/okta-sdk-php/blob/develop/src/Generated/Users/User.php#L41

This would mean you could do something like `User::create(['activate'=>false])` which should not send activation emails by default.

**Comment by LarBearrr** [comment]
Ah, I see what our issue is. We’re using v1.0 of the SDK which doesn’t include this parameter for creating users.

**Comment by bretterer** [comment]
@LarBearrr - Doing some repo cleanup, and it appears this issue is in fact resolved with the updated SDK.  If you are still having this issue, please feel free to re-open the report.
