### ISSUE TITLE
Question: How to confirm email changes?

### ISSUE THREAD

**Issue by LarryBarker** [okta/okta-sdk-php#76]
We are currently using the sample provided in the docs to update user profiles:
```
$user = new \Okta\Users\User();
$foundUser = $user->get($model->okta_id);
$profile = $foundUser->getProfile();
$profile->firstName = $model->first_name;
$profile->lastName = $model->last_name;
$profile->login = $model->email;
$profile->email = $model->email;
$foundUser->setProfile($profile);
```
We have found this does not fire the confirmation email like the Okta Dashboard does. Obviously this is problematic as users can change their email to anything they wish.

I'm sure there is a way to do this with the SDK, I am just unsure of which classes and methods to use. Any feedback is greatly appreciated. Thanks!

**Comment by bretterer** [comment]
@LarBearrr I would just like to check that you are saving the user after setting the profile.  If you are, I am not 100% sure why it would not be resending the email, as this should be handled through the api itself.

**Comment by bretterer** [comment]
@LarryBarker Closing this as stale. If you are still having the issue, please feel free to re-open this ticket or create a new one with as much detail as possible. Thanks!
