### ISSUE TITLE
Support Symfony 5

### ISSUE THREAD

**Issue by Janicules** [okta/okta-sdk-php#91]
Update the composer.json file to handle Symfony 5

**Comment by bretterer** [comment]
Thanks for the request and the PR.  We are working on a new version of the SDK right now, so I will include this into v2.0

**Comment by ajardin** [comment]
Hello @bretterer, is there any ETA for the 2.0.0 release? 🙂

**Comment by bretterer** [comment]
I am not sure of the timeline for the release of 2.0, but things are being developed in the `sdk_v2` branch that can be used.

**Comment by ajardin** [comment]
Thanks for your quick reply! I will take a look at this branch then.

**Comment by bretterer** [comment]
@ajardin ya, thats correct.  It has not been updated yet for symfony 5.  Give me about an hour and ill put an update for this as long as everything works

**Comment by bretterer** [comment]
@ajardin can you confirm if https://github.com/okta/okta-sdk-php/pull/104 helps your use case?

**Comment by ajardin** [comment]
I confirm that the installation on a Symfony 5.1 project is working.

**Comment by bretterer** [comment]
Resolved with #104
